import type { SeedCard } from "../lib/game-types";

// Keep this answer-bearing collection on the Convex side, never in a client bundle.
// Source research and reuse terms: docs/content-provenance.md.
export const seedCards: SeedCard[] = [
  {
    key: "word-absquatulate",
    category: "Odd words",
    question: "What does the old American verb 'absquatulate' mean?",
    answer: "To leave abruptly or make off.",
    source: {
      title: "Webster's 1913 — Absquatulate",
      url: "https://www.websters1913.com/words/Absquatulate",
      note: "Original question; condensed public-domain dictionary definition. The entry labels this a jocular American word.",
    },
  },
  {
    key: "word-anfractuosity",
    category: "Odd words",
    question: "What quality does 'anfractuosity' describe?",
    answer: "Being full of winding turns and twists.",
    source: {
      title: "Webster's 1913 — Anfractuosity",
      url: "https://www.websters1913.com/words/Anfractuosity",
      note: "Original question; paraphrase of public-domain sense 1, rather than the anatomical sense.",
    },
  },
  {
    key: "word-brontolith",
    category: "Odd words",
    question: "What would someone who found a 'brontolith' have picked up?",
    answer: "A meteorite: a stone or metal mass that fell from space.",
    source: {
      title: "Webster's 1913 — Brontolith",
      url: "https://www.websters1913.com/words/Brontolith",
      note: "Original question; public-domain entry defines it as an aerolite. The dictionary's Aërolite entry confirms the meteorite meaning.",
    },
  },
  {
    key: "word-crapulence",
    category: "Odd words",
    question: "What unpleasant condition is called 'crapulence'?",
    answer: "Sickness from eating or drinking too much.",
    source: {
      title: "Webster's 1913 — Crapulence",
      url: "https://www.websters1913.com/words/Crapulence",
      note: "Original question; condensed public-domain definition describing sickness from intemperance or surfeit.",
    },
  },
  {
    key: "word-erinaceous",
    category: "Odd words",
    question: "If something is 'erinaceous', what is it like?",
    answer: "Like a hedgehog.",
    source: {
      title: "Webster's 1913 — Erinaceous",
      url: "https://www.websters1913.com/words/Erinaceous",
      note: "Original question; shortened public-domain definition, which says hedgehog-like or characteristic of a hedgehog.",
    },
  },
  {
    key: "word-floccillation",
    category: "Odd words",
    question: "In old medical writing, what behavior was called 'floccillation'?",
    answer: "A delirious patient picking at the bedclothes.",
    source: {
      title: "Webster's 1913 — Floccillation",
      url: "https://www.websters1913.com/words/Floccillation",
      note: "Original question; condensed public-domain historical medical definition, not medical advice.",
    },
  },
  {
    key: "word-logomachy",
    category: "Odd words",
    question: "Outside the name of a word game, what is a 'logomachy'?",
    answer: "A quarrel over words or their meanings.",
    source: {
      title: "Webster's 1913 — Logomachy",
      url: "https://www.websters1913.com/words/Logomachy",
      note: "Original question; paraphrase of public-domain sense 1. The question excludes the separate word-game sense.",
    },
  },
  {
    key: "word-lucubration",
    category: "Odd words",
    question: "In its literal older sense, what activity is 'lucubration'?",
    answer: "Studying at night by candlelight.",
    source: {
      title: "Webster's 1913 — Lucubration",
      url: "https://www.websters1913.com/words/Lucubration",
      note: "Original question; condensed public-domain sense 1, nocturnal study rather than the resulting written work.",
    },
  },
  {
    key: "word-nidification",
    category: "Odd words",
    question: "What is an animal doing when it engages in 'nidification'?",
    answer: "Building a nest.",
    source: {
      title: "Webster's 1913 — Nidification",
      url: "https://www.websters1913.com/words/Nidification",
      note: "Original question; shortened public-domain definition of the nest-building process.",
    },
  },
  {
    key: "word-nugacity",
    category: "Odd words",
    question: "What sort of talk or behavior is 'nugacity'?",
    answer: "Trifling, futile talk or behavior.",
    source: {
      title: "Webster's 1913 — Nugacity",
      url: "https://www.websters1913.com/words/Nugacity",
      note: "Original question; condensed public-domain definition. The entry marks the word rare.",
    },
  },
  {
    key: "word-oscitant",
    category: "Odd words",
    question: "In its literal sense, what is an 'oscitant' person doing?",
    answer: "Yawning or gaping.",
    source: {
      title: "Webster's 1913 — Oscitant",
      url: "https://www.websters1913.com/words/Oscitant",
      note: "Original question; public-domain sense 1, lightly shortened. The figurative sleepy or careless sense is not asked.",
    },
  },
  {
    key: "word-pandiculation",
    category: "Odd words",
    question: "What bodily action is called 'pandiculation'?",
    answer: "Stretching and stiffening the body and limbs, as when drowsy.",
    source: {
      title: "Webster's 1913 — Pandiculation",
      url: "https://www.websters1913.com/words/Pandiculation",
      note: "Original question; condensed public-domain definition. This card asks about stretching, not just yawning.",
    },
  },
  {
    key: "word-quiddity",
    category: "Odd words",
    question: "In philosophy, what is a thing's 'quiddity'?",
    answer: "Its essential nature: what makes it the thing it is.",
    source: {
      title: "Webster's 1913 — Quiddity",
      url: "https://www.websters1913.com/words/Quiddity",
      note: "Original question; paraphrase of public-domain sense 1. The separate quibble sense is excluded by the context.",
    },
  },
  {
    key: "word-sciolism",
    category: "Odd words",
    question: "What sort of knowledge is 'sciolism'?",
    answer: "Shallow or superficial knowledge.",
    source: {
      title: "Webster's 1913 — Sciolism",
      url: "https://www.websters1913.com/words/Sciolism",
      note: "Original question; condensed public-domain dictionary definition.",
    },
  },
  {
    key: "word-sternutation",
    category: "Odd words",
    question: "What everyday bodily event is 'sternutation'?",
    answer: "Sneezing.",
    source: {
      title: "Webster's 1913 — Sternutation",
      url: "https://www.websters1913.com/words/Sternutation",
      note: "Original question; public-domain definition shortened from the act of sneezing.",
    },
  },
  {
    key: "word-tarantism",
    category: "Odd words",
    question: "What urge characterized the historical condition called 'tarantism'?",
    answer: "An uncontrollable desire to dance, once blamed on a tarantula bite.",
    source: {
      title: "Webster's 1913 — Tarantism",
      url: "https://www.websters1913.com/words/Tarantism",
      note: "Original paraphrase of a public-domain historical definition. The spider-bite explanation is an old belief, not a present-day medical claim.",
    },
  },
  {
    key: "word-velleity",
    category: "Odd words",
    question: "How strong a wish is a 'velleity'?",
    answer: "A faint, incomplete wish, short of a firm intention.",
    source: {
      title: "Webster's 1913 — Velleity",
      url: "https://www.websters1913.com/words/Velleity",
      note: "Original question; paraphrase of the public-domain definition of minimal desire or incomplete volition.",
    },
  },
  {
    key: "word-wamble",
    category: "Odd words",
    question: "In the older bodily sense, what is 'a wamble'?",
    answer: "An upset stomach or feeling of nausea.",
    source: {
      title: "Webster's 1913 — Wamble",
      url: "https://www.websters1913.com/words/Wamble",
      note: "Original question; condensed public-domain noun definition, rather than the verb meaning to move irregularly.",
    },
  },
  {
    key: "object-bickern",
    category: "Curious objects",
    question: "What is a metalworker's 'bickern'?",
    answer: "An anvil with a pointed beak or horn.",
    source: {
      title: "Webster's 1913 — Bickern",
      url: "https://www.websters1913.com/words/Bickern",
      note: "Original question; condensed public-domain dictionary definition.",
    },
  },
  {
    key: "object-burin",
    category: "Curious objects",
    question: "What would an engraver do with a 'burin'?",
    answer: "Cut lines into metal with its sharp steel point.",
    source: {
      title: "Webster's 1913 — Burin",
      url: "https://www.websters1913.com/words/Burin",
      note: "Original question; paraphrase of public-domain sense 1 describing the engraving tool.",
    },
  },
  {
    key: "object-chatelaine",
    category: "Curious objects",
    question: "What was the purpose of a wearable 'chatelaine'?",
    answer: "To hang keys, a watch, and trinkets from chains at the waist.",
    source: {
      title: "Webster's 1913 — Chatelaine",
      url: "https://www.websters1913.com/words/Chatelaine",
      note: "Original question; paraphrase of the public-domain description of a waist hook or brooch with short chains.",
    },
  },
  {
    key: "object-clepsydra",
    category: "Curious objects",
    question: "How does a 'clepsydra' measure something?",
    answer: "It measures time by water flowing through a small opening.",
    source: {
      title: "Webster's 1913 — Clepsydra",
      url: "https://www.websters1913.com/words/Clepsydra",
      note: "Original question; paraphrase of the public-domain water-clock definition.",
    },
  },
  {
    key: "object-dibble",
    category: "Curious objects",
    question: "What is a gardener's 'dibble' used for?",
    answer: "Making holes in soil for seeds or young plants.",
    source: {
      title: "Webster's 1913 — Dibble",
      url: "https://www.websters1913.com/words/Dibble",
      note: "Original question; condensed public-domain noun definition of the pointed planting tool.",
    },
  },
  {
    key: "object-fid",
    category: "Curious objects",
    question: "What does a rope-maker do with a pointed wooden 'fid'?",
    answer: "Open the rope's strands so they can be spliced.",
    source: {
      title: "Webster's 1913 — Fid",
      url: "https://www.websters1913.com/words/Fid",
      note: "Original question; paraphrase of public-domain sense 3. The material and context distinguish it from a mast-supporting fid.",
    },
  },
  {
    key: "object-fipple",
    category: "Curious objects",
    question: "In the old musical-instrument sense, what is a 'fipple'?",
    answer: "A stopper or plug in a wind instrument.",
    source: {
      title: "Webster's 1913 — Fipple",
      url: "https://www.websters1913.com/words/Fipple",
      note: "Original question; condensed public-domain definition. The entry explicitly marks this sense obsolete.",
    },
  },
  {
    key: "object-fleam",
    category: "Curious objects",
    question: "What was a surgeon's or farrier's 'fleam' used to do?",
    answer: "Open a vein or lance tissue with a small sharp blade.",
    source: {
      title: "Webster's 1913 — Fleam",
      url: "https://www.websters1913.com/words/Fleam",
      note: "Original question; paraphrase of the public-domain surgical and farriery definition. A historical object, not treatment advice.",
    },
  },
  {
    key: "object-gnomon",
    category: "Curious objects",
    question: "What job does the 'gnomon' of a sundial perform?",
    answer: "It casts the shadow that indicates the time.",
    source: {
      title: "Webster's 1913 — Gnomon",
      url: "https://www.websters1913.com/words/Gnomon",
      note: "Original question; paraphrase of public-domain sense 1, the sundial's style or pin.",
    },
  },
  {
    key: "object-pipkin",
    category: "Curious objects",
    question: "What kind of household vessel was a 'pipkin'?",
    answer: "A small earthenware pot for boiling things.",
    source: {
      title: "Webster's 1913 — Pipkin",
      url: "https://www.websters1913.com/words/Pipkin",
      note: "Original question; paraphrase of the public-domain definition, a small earthen boiler.",
    },
  },
  {
    key: "object-porringer",
    category: "Curious objects",
    question: "What would a child traditionally use a 'porringer' for?",
    answer: "Eating porridge from a small bowl or cup.",
    source: {
      title: "Webster's 1913 — Porringer",
      url: "https://www.websters1913.com/words/Porringer",
      note: "Original question; paraphrase of the public-domain porridge-dish definition, especially a vessel for feeding children.",
    },
  },
  {
    key: "object-quern",
    category: "Curious objects",
    question: "How would someone use a 'quern' to prepare food?",
    answer: "Turn its upper stone by hand to grind grain.",
    source: {
      title: "Webster's 1913 — Quern",
      url: "https://www.websters1913.com/words/Quern",
      note: "Original question; paraphrase of the public-domain hand-mill definition.",
    },
  },
  {
    key: "object-scrutoire",
    category: "Curious objects",
    question: "What piece of furniture was called a 'scrutoire'?",
    answer: "A writing desk.",
    source: {
      title: "Webster's 1913 — Scrutoire",
      url: "https://www.websters1913.com/words/Scrutoire",
      note: "Original question; the brief public-domain definition is retained.",
    },
  },
  {
    key: "object-snath",
    category: "Curious objects",
    question: "Which part of a scythe is its 'snath'?",
    answer: "The handle or shaft that the blade attaches to.",
    source: {
      title: "Webster's 1913 — Snath",
      url: "https://www.websters1913.com/words/Snath",
      note: "Original question; paraphrase of the public-domain definition, the handle of a scythe.",
    },
  },
  {
    key: "object-strigil",
    category: "Curious objects",
    question: "What did ancient Greek and Roman bathers do with a 'strigil'?",
    answer: "Scrape their skin clean.",
    source: {
      title: "Webster's 1913 — Strigil",
      url: "https://www.websters1913.com/words/Strigil",
      note: "Original question; condensed public-domain description of the bathing scraper.",
    },
  },
  {
    key: "object-thurible",
    category: "Curious objects",
    question: "What is a 'thurible' used for during a church service?",
    answer: "Burning incense in a metal censer, often suspended on chains.",
    source: {
      title: "Webster's 1913 — Thurible",
      url: "https://www.websters1913.com/words/Thurible",
      note: "Original question; condensed public-domain description of the incense vessel.",
    },
  },
  {
    key: "object-triblet",
    category: "Curious objects",
    question: "What is a 'triblet' in a metalworker's workshop?",
    answer: "A mandrel around which metal is shaped into rings or tubes.",
    source: {
      title: "Webster's 1913 — Triblet",
      url: "https://www.websters1913.com/words/Triblet",
      note: "Original question; synthesis of the public-domain entry's ring-making tool, tube-forming cylinder, and tapering mandrel senses.",
    },
  },
  {
    key: "object-tympan",
    category: "Curious objects",
    question: "What was a printer's 'tympan' used for?",
    answer: "Holding a blank sheet in position to be pressed onto the printing form.",
    source: {
      title: "Webster's 1913 — Tympan",
      url: "https://www.websters1913.com/words/Tympan",
      note: "Original question; paraphrase of public-domain printing sense 3, a frame covered with parchment or cloth.",
    },
  },
  {
    key: "nature-sea-cucumber-defense",
    category: "Wild nature",
    question: "What startling escape tactic can some sea cucumbers use when threatened?",
    answer: "Eject some internal organs from their rear end, then grow the missing parts back.",
    source: {
      title: "NOAA — Are sea cucumbers vegetables?",
      url: "https://oceanservice.noaa.gov/facts/seacuke.html",
      note: "Original factual paraphrase of NOAA public-information text. This defense belongs to some species, not every sea cucumber.",
    },
  },
  {
    key: "nature-christmas-tree-worm",
    category: "Wild nature",
    question: "What are the colorful 'trees' on a Christmas tree worm actually for?",
    answer: "Breathing and catching tiny drifting food particles.",
    source: {
      title: "NOAA — What are Christmas tree worms?",
      url: "https://oceanservice.noaa.gov/facts/xmas-tree.html",
      note: "Original factual paraphrase of NOAA public-information text describing the crowns and their radioles.",
    },
  },
  {
    key: "nature-rimicaris-food",
    category: "Wild nature",
    question: "Rimicaris shrimp at deep-sea vents have an unusual food supply. Where does it grow?",
    answer: "On their own bodies: they eat bacteria that grow there.",
    source: {
      title: "NOAA Ocean Exploration — Wild and Bizarre Marine Life",
      url: "https://oceanexplorer.noaa.gov/explainers/marine-life/",
      note: "Original factual paraphrase of Emily Crum's NOAA article, Chemosynthesis section and Rimicaris photograph caption. No image reused.",
    },
  },
  {
    key: "nature-armored-searobin",
    category: "Wild nature",
    question: "How does an armored searobin take a stroll across the seafloor?",
    answer: "It walks on thick, stiff rays of its pectoral fins.",
    source: {
      title: "NOAA Ocean Exploration — Wild and Bizarre Marine Life",
      url: "https://oceanexplorer.noaa.gov/explainers/marine-life/",
      note: "Original factual paraphrase of Emily Crum's NOAA article, The Armored Searobin section; no media reused.",
    },
  },
  {
    key: "nature-dandelion-siphonophore",
    category: "Wild nature",
    question: "How does a dandelion siphonophore keep itself in place near the ocean bottom?",
    answer: "It tethers itself to the seafloor with its tentacles.",
    source: {
      title: "NOAA Ocean Exploration — Wild and Bizarre Marine Life",
      url: "https://oceanexplorer.noaa.gov/explainers/marine-life/",
      note: "Original factual paraphrase of Emily Crum's NOAA article, Siphonophores section and Rhodaliidae caption. No image reused.",
    },
  },
  {
    key: "nature-red-camouflage",
    category: "Wild nature",
    question: "Why can a bright red body help a deep-sea animal stay hidden?",
    answer: "Red sunlight does not reach those depths, so a red body looks dark there.",
    source: {
      title: "NOAA Ocean Exploration — Wild and Bizarre Marine Life",
      url: "https://oceanexplorer.noaa.gov/explainers/marine-life/",
      note: "Original factual paraphrase of The Invisibility of Being Red section. This concerns ambient sunlight, not a claim that no animal makes red light.",
    },
  },
  {
    key: "nature-venus-flower-basket",
    category: "Wild nature",
    question:
      "Why might a pair of little shrimp spend their whole adult lives inside a Venus flower basket sponge?",
    answer: "They grow too large to escape through the sponge's skeleton.",
    source: {
      title: "NOAA — What is a glass sponge?",
      url: "https://oceanservice.noaa.gov/facts/glass-sponge.html",
      note: "Original factual paraphrase of NOAA public-information text describing the sponge's resident crustacean pair.",
    },
  },
  {
    key: "nature-parrotfish-sand",
    category: "Wild nature",
    question: "How do parrotfish help manufacture white beach sand?",
    answer: "They grind swallowed coral skeleton material in their guts and poop it out as sand.",
    source: {
      title: "NOAA — How does sand form?",
      url: "https://oceanservice.noaa.gov/facts/sand.html",
      note: "Original factual paraphrase of NOAA public-information text. Parrotfish supply some white sand, not all sand or every white beach.",
    },
  },
  {
    key: "nature-vampire-squid-defense",
    category: "Wild nature",
    question: "What can a threatened vampire squid release instead of an ink cloud?",
    answer: "A cloud of sticky, glowing mucus.",
    source: {
      title: "NOAA — The vampire squid and the vampire fish",
      url: "https://oceanservice.noaa.gov/facts/vampire-squid-fish.html",
      note: "Original factual paraphrase of NOAA public-information text on bioluminescent defensive mucus. No third-party photograph reused.",
    },
  },
  {
    key: "nature-man-o-war-colony",
    category: "Wild nature",
    question: "Why is calling a Portuguese man o' war one ordinary jellyfish misleading?",
    answer: "It is a colony of specialized, connected individuals that work together.",
    source: {
      title: "NOAA — What is a Portuguese Man o' War?",
      url: "https://oceanservice.noaa.gov/facts/portuguese-man-o-war.html",
      note: "Original factual paraphrase of NOAA public-information text describing the colony's zooids; no image reused.",
    },
  },
  {
    key: "nature-nautilus-chambers",
    category: "Wild nature",
    question: "What useful job do the unoccupied chambers in a nautilus shell perform?",
    answer: "They act as ballast tanks, helping it adjust its buoyancy.",
    source: {
      title: "NOAA — What is a nautilus?",
      url: "https://oceanservice.noaa.gov/facts/nautilus.html",
      note: "Original factual paraphrase of NOAA public-information text about shell chambers and the siphuncle.",
    },
  },
  {
    key: "nature-platypus-gravel",
    category: "Wild nature",
    question: "An adult platypus has no teeth. What does it use to help mash its meal?",
    answer: "Bits of gravel gathered with its food.",
    source: {
      title: "NOAA — What is a platypus?",
      url: "https://oceanservice.noaa.gov/facts/platypus.html",
      note: "Original factual paraphrase of NOAA public-information text describing gravel-assisted feeding. The question specifies adults.",
    },
  },
  {
    key: "nature-oyster-spat",
    category: "Wild nature",
    question: "On an oyster farm, what does 'spat' refer to?",
    answer: "Young oysters that have settled and attached to a surface.",
    source: {
      title: "NOAA — What is spat?",
      url: "https://oceanservice.noaa.gov/facts/spat.html",
      note: "Original factual paraphrase of NOAA public-information text on oyster larval settlement.",
    },
  },
  {
    key: "nature-whale-fall",
    category: "Wild nature",
    question: "What is a 'whale fall' to a deep-sea biologist?",
    answer: "A sunken whale carcass that feeds a seafloor community, sometimes for decades.",
    source: {
      title: "NOAA — What is a whale fall?",
      url: "https://oceanservice.noaa.gov/facts/whale-fall.html",
      note: "Original factual paraphrase of NOAA public-information text. The long-lived food source includes the bones and their chemical breakdown.",
    },
  },
  {
    key: "nature-horseshoe-crab-blood",
    category: "Wild nature",
    question: "Why has horseshoe crab blood been used to check medicines and medical equipment?",
    answer: "It clots in response to bacterial toxins, revealing contamination.",
    source: {
      title: "NOAA — Are horseshoe crabs really crabs?",
      url: "https://oceanservice.noaa.gov/facts/horseshoe-crab.html",
      note: "Original factual paraphrase of NOAA public-information text on toxin detection; no claims about harvesting safety or current regulations.",
    },
  },
  {
    key: "nature-green-turtle-name",
    category: "Wild nature",
    question: "Which surprisingly hidden feature gives the green sea turtle its name?",
    answer: "Its greenish body fat, not its shell.",
    source: {
      title: "NOAA — What makes the green turtle...green?",
      url: "https://oceanservice.noaa.gov/facts/green-turtle.html",
      note: "Original factual paraphrase of NOAA public-information text. The card states the namesake without treating the proposed dietary cause as certain.",
    },
  },
  {
    key: "nature-carrageenan",
    category: "Wild nature",
    question: "Where does carrageenan, a thickener used in some foods and toothpastes, come from?",
    answer: "Red algae, processed to extract their thickening compounds.",
    source: {
      title: "NOAA — What does peanut butter have to do with the ocean?",
      url: "https://oceanservice.noaa.gov/facts/peanutbutter.html",
      note: "Original factual paraphrase of NOAA public-information text. Some products use it; the card does not say every brand contains it.",
    },
  },
  {
    key: "nature-barnacle-cement",
    category: "Wild nature",
    question: "How do barnacles fasten themselves so firmly to a ship's hull?",
    answer: "They secrete a powerful, fast-setting natural cement.",
    source: {
      title: "NOAA — What are barnacles?",
      url: "https://oceanservice.noaa.gov/facts/barnacles.html",
      note: "Original factual paraphrase of NOAA public-information text about barnacle adhesive.",
    },
  },
  {
    key: "space-gemini-sandwich",
    category: "Space oddities",
    question: "What unauthorized snack did John Young pull from his spacesuit during Gemini III?",
    answer: "A corned beef sandwich.",
    source: {
      title: "NASA History — Fallout from the Unauthorized Gemini III Space Sandwich",
      url: "https://www.nasa.gov/history/fallout-from-the-unauthorized-gemini-iii-space-sandwich/",
      note: "Original game wording based on Jennifer Ross-Nazzal's mission history and its flight-record account. No quotations or NASA media reproduced.",
    },
  },
  {
    key: "space-apollo-golf-tool",
    category: "Space oddities",
    question:
      "What improvised piece of sports equipment did Alan Shepard make from a lunar sample-tool handle?",
    answer: "A golf club, by attaching the head of a six-iron.",
    source: {
      title: "NASA History — 50 Years Ago: Apollo 14 Lands at Fra Mauro",
      url: "https://www.nasa.gov/history/50-years-ago-apollo-14-lands-at-fra-mauro/",
      note: "Original game wording based on John Uri's account of the second moonwalk. No quotations or media reproduced.",
    },
  },
  {
    key: "space-apollo-feather",
    category: "Space oddities",
    question: "Why did Apollo 15 use a falcon feather alongside a geological hammer on the Moon?",
    answer:
      "To drop them together and show that both fall at the same rate without air resistance.",
    source: {
      title: "NASA Science — The Apollo 15 Hammer-Feather Drop",
      url: "https://science.nasa.gov/resource/the-apollo-15-hammer-feather-drop/",
      note: "Original game wording based on the demonstration summary and the cited Apollo 15 Preliminary Science Report, p. 2-11. No transcript or video reused.",
    },
  },
  {
    key: "space-gemini-music",
    category: "Space oddities",
    question:
      "What instruments did Gemini VI astronauts use for their live orbital performance of 'Jingle Bells'?",
    answer: "A tiny harmonica and a handful of small bells.",
    source: {
      title: "NASA History — 55 Years Ago: The Spirit of 76 — The First Rendezvous in Space",
      url: "https://www.nasa.gov/history/55-years-ago-the-spirit-of-76-the-first-rendezvous-in-space/",
      note: "Original game wording based on the mission account of the December 1965 performance; no lyrics, recording, or museum image reused.",
    },
  },
  {
    key: "space-curiosity-wheel-code",
    category: "Space oddities",
    question: "Why do Curiosity's wheels stamp a repeating Morse-code pattern into Martian soil?",
    answer: "The marks provide visual reference points to measure travel and detect wheel slip.",
    source: {
      title: "NASA JPL — Rover Leaves Tracks in Morse Code",
      url: "https://www.jpl.nasa.gov/news/rover-leaves-tracks-in-morse-code/",
      note: "Original factual paraphrase of JPL's engineering account of visual odometry. The pattern spells JPL; no copyrighted JPL text or imagery copied.",
    },
  },
  {
    key: "space-moon-trees",
    category: "Space oddities",
    question: "What makes an original Apollo 'Moon Tree' different from an ordinary tree?",
    answer: "It grew on Earth from a seed carried around the Moon aboard Apollo 14.",
    source: {
      title: "NASA History — Moon Trees",
      url: "https://www.nasa.gov/history/moon-trees/",
      note: "Original game wording based on the Apollo 14 Moon Trees section. The seeds orbited with Stuart Roosa; they were not planted on the Moon.",
    },
  },
  {
    key: "space-mercury-double-sunrise",
    category: "Space oddities",
    question:
      "What strange trick can the morning Sun perform when viewed from some places on Mercury?",
    answer: "Rise, dip back below the horizon, then rise again.",
    source: {
      title: "NASA Science — Mercury Facts",
      url: "https://science.nasa.gov/mercury/facts/",
      note: "Original game wording based on the Orbit and Rotation section. The effect applies to some locations, not every Mercurian sunrise.",
    },
  },
  {
    key: "space-mercury-crater-names",
    category: "Space oddities",
    question: "What sort of people lend their names to craters on Mercury?",
    answer: "Deceased artists, musicians, and writers.",
    source: {
      title: "NASA Science — Mercury Facts",
      url: "https://science.nasa.gov/mercury/facts/",
      note: "Original game wording based on the Surface section's crater-naming convention; no article prose copied.",
    },
  },
  {
    key: "space-zoozve-name",
    category: "Space oddities",
    question: "How did Venus's companion asteroid Zoozve get its peculiar name?",
    answer:
      "An illustrator misread his handwritten '2002 VE' as 'Zoozve' on a children's space poster.",
    source: {
      title: "NASA Science — Venus Facts: How Zoozve Got Its Name",
      url: "https://science.nasa.gov/venus/venus-facts/",
      note: "Original factual paraphrase of the naming history. The artist's mistake became the asteroid's official name in 2024; no poster art reused.",
    },
  },
  {
    key: "space-venus-rotation",
    category: "Space oddities",
    question: "What odd comparison can you make between one full spin of Venus and one Venus year?",
    answer: "One full spin takes longer than the planet's entire trip around the Sun.",
    source: {
      title: "NASA Science — Venus Facts",
      url: "https://science.nasa.gov/venus/venus-facts/",
      note: "Original game wording based on Orbit and Rotation: about 243 Earth days per spin and 225 per orbit. A full spin is not a sunrise-to-sunrise day.",
    },
  },
  {
    key: "space-uranus-george",
    category: "Space oddities",
    question: "Whom did William Herschel try to honor by naming Uranus 'Georgium Sidus'?",
    answer: "King George III of Britain.",
    source: {
      title: "NASA Science — Uranus Facts",
      url: "https://science.nasa.gov/uranus/facts/",
      note: "Original game wording based on the Namesake section's account of Herschel's unsuccessful proposed name.",
    },
  },
  {
    key: "space-uranus-literary-moons",
    category: "Space oddities",
    question:
      "Where do the names of Uranus's moons come from, instead of the usual classical gods?",
    answer: "Characters in works by William Shakespeare and Alexander Pope.",
    source: {
      title: "NASA Science — Uranus Facts",
      url: "https://science.nasa.gov/uranus/facts/",
      note: "Original game wording based on the Moons section. No source wording beyond proper names is reproduced.",
    },
  },
  {
    key: "space-uranus-long-winter",
    category: "Space oddities",
    question: "Why can a pole of Uranus face a winter with roughly 21 years of darkness?",
    answer:
      "The planet spins almost on its side, leaving a pole turned away from the Sun for years.",
    source: {
      title: "NASA Science — Uranus Facts",
      url: "https://science.nasa.gov/uranus/facts/",
      note: "Original game wording based on the Orbit and Rotation section's extreme axial tilt and long polar winter.",
    },
  },
  {
    key: "space-triton-backwards",
    category: "Space oddities",
    question: "What is unusual about the direction Neptune's large moon Triton travels?",
    answer: "It orbits against the direction in which Neptune spins.",
    source: {
      title: "NASA Science — Triton",
      url: "https://science.nasa.gov/neptune/moons/triton/",
      note: "Original game wording based on the Overview section's retrograde orbit. The card makes no claim that all retrograde moons are unique.",
    },
  },
  {
    key: "space-titan-lakes",
    category: "Space oddities",
    question: "What fills the lakes and seas on the surface of Saturn's moon Titan?",
    answer: "Liquid hydrocarbons, especially methane and ethane.",
    source: {
      title: "NASA Science — Titan Facts",
      url: "https://science.nasa.gov/saturn/moons/titan/facts/",
      note: "Original game wording based on the Introduction and Surface sections. Surface lakes are distinguished from the possible subsurface water ocean.",
    },
  },
  {
    key: "space-titan-dunes",
    category: "Space oddities",
    question: "What is the dark 'sand' in Titan's vast dune fields made from?",
    answer: "Carbon-rich hydrocarbon grains rather than ordinary rocky sand.",
    source: {
      title: "NASA Science — Titan Facts",
      url: "https://science.nasa.gov/saturn/moons/titan/facts/",
      note: "Original game wording based on the Surface and Atmosphere sections describing organic material settling into dune fields.",
    },
  },
  {
    key: "space-enceladus-ring",
    category: "Space oddities",
    question: "How does the little moon Enceladus help keep Saturn's E ring supplied?",
    answer:
      "Its jets spray icy particles into space, and some spread around Saturn as ring material.",
    source: {
      title: "NASA Science — Enceladus",
      url: "https://science.nasa.gov/saturn/moons/enceladus/",
      note: "Original game wording based on the Overview section. Only some ejected material enters the ring; much falls back onto the moon.",
    },
  },
  {
    key: "space-io-missing-craters",
    category: "Space oddities",
    question: "Why does Jupiter's moon Io lack the large impact craters seen on many other moons?",
    answer: "Constant volcanic deposits resurface it faster than large craters can accumulate.",
    source: {
      title: "NASA Science — Io",
      url: "https://science.nasa.gov/jupiter/jupiter-moons/io/",
      note: "Original game wording based on the opening explanation of rapid volcanic resurfacing; no NASA or partner media reused.",
    },
  },
];
