#!/usr/bin/env node
// Regenerates the two artifacts derived from convex/deck/:
//
//   convex/deck/catalog.ts   the static pack registry Convex bundles
//   docs/content-index.md    the per-card provenance index
//
// Convex bundles with esbuild, so every pack must be a static import; and a
// 1,300-card provenance table cannot be maintained by hand without drifting
// from the cards it documents. Both fall out of the deck directory instead.
// `tests/content.test.ts` fails when either artifact is stale.
//
// Usage: pnpm catalog

import { readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { createServer } from "vite";

const root = fileURLToPath(new URL("../", import.meta.url));
const deckDir = path.join(root, "convex", "deck");

export const INFRASTRUCTURE_MODULES = new Set([
  "audit.ts",
  "catalog.ts",
  "types.ts",
  "validate.ts",
]);

const packPattern = /export\s+const\s+(\w+)\s*=\s*definePack\(/;
const sortPattern = /["']?sort["']?:\s*(-?\d+)/;

/** Discover pack modules and the order they should be registered in. */
export async function readPackModules() {
  const entries = [];
  for (const file of await readdir(deckDir)) {
    if (!file.endsWith(".ts") || INFRASTRUCTURE_MODULES.has(file)) continue;
    const source = await readFile(path.join(deckDir, file), "utf8");
    const exported = packPattern.exec(source)?.[1];
    if (!exported) throw new Error(`No definePack export found in convex/deck/${file}`);
    const sort = sortPattern.exec(source)?.[1];
    if (sort === undefined) throw new Error(`No pack sort value found in convex/deck/${file}`);
    entries.push({ module: file.replace(/\.ts$/, ""), exported, sort: Number(sort) });
  }
  entries.sort((a, b) => a.sort - b.sort || a.exported.localeCompare(b.exported));
  const clash = entries.find((entry, index) => index > 0 && entries[index - 1].sort === entry.sort);
  if (clash) throw new Error(`Duplicate pack sort value ${clash.sort} on ${clash.module}`);
  return entries;
}

export function renderCatalog(entries) {
  return `import type { SeedCard, SeedPack } from "./types";
${entries.map((entry) => `import { ${entry.exported} } from "./${entry.module}";`).join("\n")}

export const seedPacks: SeedPack[] = [
${entries.map((entry) => `  ${entry.exported},`).join("\n")}
];

export const seedCards: SeedCard[] = seedPacks.flatMap((pack) => pack.cards);
`;
}

const escapeCell = (text) => text.replaceAll("|", "\\|");

export function renderIndex(packs, cards) {
  const lines = [
    "<!-- Generated by `pnpm catalog`. Edit the pack modules in convex/deck/, not this file. -->",
    "",
    "# Poppycock card index",
    "",
    `Every shipped card and the source consulted for it: **${cards.length} cards** across **${packs.length} packs**.`,
    "The editorial method, reuse basis, and precision decisions behind these choices are in",
    "[content-provenance.md](content-provenance.md).",
    "",
    "| Pack | Category | Cards |",
    "| ---- | -------- | ----: |",
    ...packs.map(
      (pack) =>
        `| ${escapeCell(pack.title)} | ${escapeCell(pack.category)} | ${pack.cards.length} |`,
    ),
    `| **Total** | | **${cards.length}** |`,
    "",
  ];

  for (const pack of packs) {
    lines.push(
      `## ${pack.title}`,
      "",
      pack.blurb,
      "",
      "| Card | Source |",
      "| ---- | ------ |",
      ...pack.cards.map(
        (card) => `| \`${card.key}\` | [${escapeCell(card.source.title)}](${card.source.url}) |`,
      ),
      "",
    );
  }

  return lines.join("\n");
}

async function loadCatalog() {
  const server = await createServer({
    root,
    configFile: false,
    server: { middlewareMode: true },
    appType: "custom",
    logLevel: "error",
  });
  try {
    return await server.ssrLoadModule("/convex/deck/catalog.ts");
  } finally {
    await server.close();
  }
}

export async function generateCatalog() {
  const entries = await readPackModules();
  await writeFile(path.join(deckDir, "catalog.ts"), renderCatalog(entries));

  const { seedPacks, seedCards } = await loadCatalog();
  await writeFile(path.join(root, "docs", "content-index.md"), renderIndex(seedPacks, seedCards));

  console.log(
    `Wrote convex/deck/catalog.ts (${entries.length} packs) and docs/content-index.md (${seedCards.length} cards).`,
  );
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await generateCatalog();
}
